layout_spectrum: 0.3928571
color:
  saturation: 0.3665872
  lightness: 0.9272634
  brandStrength: 0.9210526
  brandColors:
    - '#171719'
    - '#CFCFCF'
    - '#AFAFAF'
    - '#4A454B'
    - '#686369'
  rhythmicContrast: 0.5352148
typography_spectrum: 0.141604
name: Damon Bennett
