collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.4155784
  lightness: 1
  brandColors:
    - '#0A0A0A'
    - '#FFFFFF'
    - '#DC9A22'
    - '#868686'
    - '#B0B0B0'
  rhythmicContrast: 0.9925373
typography_spectrum: 0.255597
layout_spectrum: 0.28125
name: Damon Bennett
